### ISSUE TITLE
Add Mobile and Tablet Responsive UI

### ISSUE THREAD

**Issue by mananchawla2005** [mananchawla2005/Hacktoberfest-Repo-Checker#1]
Using Bootstrap or any other library of your choice or vanilla css, Make the website responsive to mobile and tablet sized screens.

**Comment by erdinhrmwn** [comment]
lemme work on it

**Comment by mananchawla2005** [comment]
@erdinhrmwn sure

**Comment by iamrishavraj1** [comment]
Hello Sir, Can You Please Assign me this Issue.

**Comment by mananchawla2005** [comment]
> Hello Sir, Can You Please Assign me this Issue.

Sure 👍

**Comment by mananchawla2005** [comment]
Thanks
