### ISSUE TITLE
Add checks for hacktoberfest banned repo & PR accepted for api

### ISSUE THREAD

**Issue by sadakchap** [mananchawla2005/Hacktoberfest-Repo-Checker#10]
Update API endpoint to check 
 - hacktoberfest banned repo
 - Pull request status

**Comment by sadakchap** [comment]
Hi @mananchawla2005 , can I work on this issue?

**Comment by mananchawla2005** [comment]
@sadakchap of course you can!! happy hacking 👀

**Comment by sadakchap** [comment]
Hi @mananchawla2005 , [here](https://github.com/mananchawla2005/Hacktoberfest-Repo-Checker/pull/11) is the PR for this Issue

Please, Kindly review changes and let me know if any further changes are needed

**Comment by mananchawla2005** [comment]
Thanks

**Comment by sadakchap** [comment]
> Thanks

Thanks @mananchawla2005 for helping me 😃
