### ISSUE TITLE
Corrections in README

### ISSUE THREAD

**Issue by sakshi-s** [mananchawla2005/Hacktoberfest-Repo-Checker#12]
Following corrections are suggested in README.md file.

** Start the server with "node index.js".

** Your server should be running at https://localhost:8080

**Comment by mananchawla2005** [comment]
Thanks for telling :-)

**Comment by sakshi-s** [comment]
Shall I create a PR for this?
Also, it would be great if you could suggest or open some new issues.

**Comment by mananchawla2005** [comment]
@sakshi-s you can always create your own issues  and i will assign you that
