### ISSUE TITLE
Search History

### ISSUE THREAD

**Issue by mananchawla2005** [mananchawla2005/Hacktoberfest-Repo-Checker#14]
- Store the recent searches by the user in the local storage. And display the last four on the website itself and remove the rest from the storage.

**Comment by sakshi-s** [comment]
Hey @mananchawla2005  I would like to work on this.

**Comment by mananchawla2005** [comment]
@sakshi-s Go ahead

**Comment by mananchawla2005** [comment]
@sakshi-s you working on it?

**Comment by IsautierEloise** [comment]
Hello, can you assign me this issue please ?

**Comment by mananchawla2005** [comment]
Sure 👍 you can work on this I will assign once I am on pc @IsautierEloise

**Comment by Rebaiahmed** [comment]
Hi , I want to contribute if there any open issues are features to add , feel free to ping me thanks

**Comment by mananchawla2005** [comment]
> 
> 
> Hi , I want to contribute if there any open issues are features to add , feel free to ping me thanks

Sorry but no hacktoberfest is about to end in 3 days and this repo would be of no use for a year after this!

**Comment by mananchawla2005** [comment]
@IsautierEloise you working??

**Comment by IsautierEloise** [comment]
Yes sorry, I have a lot of deadlines ! I'll finish tomorrow for sure

**Comment by mananchawla2005** [comment]
Yeah

**Comment by IsautierEloise** [comment]
I didn't realize today was the first of november I'm sorry ^^' I get the repo is not in use anymore until next year?

**Comment by mananchawla2005** [comment]
Yes 😅 but you still can make the pr if you want! @IsautierEloise
