### ISSUE TITLE
Check Other api endpoints

### ISSUE THREAD

**Issue by mananchawla2005** [mananchawla2005/Hacktoberfest-Repo-Checker#2]
Check other api endpoints also for banned repositories and pr's marked as hacktoberfest-accepted

**Comment by sadakchap** [comment]
Hi @mananchawla2005 , I would like to work on this. May I?

**Comment by mananchawla2005** [comment]
Sure @sadakchap

**Comment by sadakchap** [comment]
Hi @mananchawla2005 , I have some queries -

- since we are only taking repo url in input, which on submit makes a request to `\check` endpoint,,, should I only update the octokit query to check for banned repos or you suggest a better way

- Again, we are taking repo url, for checking pr's as hacktoberfest-accept, do we need to have different form/input field and hit different route.

Please, let me know your views 🙏

**Comment by mananchawla2005** [comment]
No it would be better if you combine it all together in one route and after checking all the conditions send the response. @sadakchap

**Comment by sadakchap** [comment]
> No it would be better if you combine it all together in one route and after checking all the conditions send the response. @sadakchap

Ok, I will try implementing that and let you know about it.

**Comment by mananchawla2005** [comment]
@sadakchap hey you still working on it?

**Comment by sadakchap** [comment]
> @sadakchap hey you still working on it?

I can't figure out how to check for banned repos 🙁.
Can you give some hints ?

**Comment by mananchawla2005** [comment]
@sadakchap check for issues like this (OpenSourceTogether/Hacktoberfest-2020#146) opened by @hacktoberfest-team on the repository,
Every banned repo has this issue with the same topic so it will be easy to identify it.

**Comment by sadakchap** [comment]
Hi @mananchawla2005 , Please check the PR, and let me know if you need any changes

**Comment by mananchawla2005** [comment]
> Hi @mananchawla2005 , Please check the PR, and let me know if you need any changes

Yeah I mentioned it in the pr itself

**Comment by sadakchap** [comment]
@mananchawla2005 , for checking close PR, should I do it in same route `/check` ??

For that, I'll checking for `/pulls/` substring, if it exists, then only checking for that specified PR.

**Comment by mananchawla2005** [comment]
@sadakchap yeah check in the same route

**Comment by mananchawla2005** [comment]
@sadakchap Well nice it works perfectly. Maybe you could open an issue and apply that to the api endpoint also??

**Comment by sadakchap** [comment]
> @sadakchap Well nice it works perfectly. Maybe you could open an issue and apply that to the api endpoint also??

Thanks @mananchawla2005 for helping me 🤗 and for patience.
I will open an issue for API

**Comment by mananchawla2005** [comment]
Thanks
