### ISSUE TITLE
Add a column for showing the user's last searched repositories

### ISSUE THREAD

**Issue by mananchawla2005** [mananchawla2005/Hacktoberfest-Repo-Checker#31]
Add a column for showing the user's last searched repositories which were eligible for hacktoberfest. The list can be saved in local storage to persist history

**Comment by neeraj15022001** [comment]
I would like to work this out.

**Comment by mananchawla2005** [comment]
@neeraj15022001 Sure added ya to here as well :)

**Comment by neeraj15022001** [comment]
Great

**Comment by neeraj15022001** [comment]
Can you check on your end if API is working and if working please send an example call

**Comment by mananchawla2005** [comment]
@neeraj15022001 Stick to one issue please. Yea its working check it again. It went down in between but now it is working. 
https://hacktoberfest.cf/api?url=https://github.com/mananchawla2005/Hacktoberfest-Repo-Checker check this link for example

**Comment by neeraj15022001** [comment]
Other issue is already done ( UI ) NOW  api work and last searched column is left. Right?

**Comment by mananchawla2005** [comment]
@neeraj15022001 Yea but api first so that I can add more issues after merging the pr

**Comment by neeraj15022001** [comment]
![Screenshot 2021-09-18 at 6 02 36 PM](https://user-images.githubusercontent.com/55191873/133888940-1fd71a32-df0c-4a84-98f5-0a096eb9c875.png)
Had you tested it in postman as i unable to access it

**Comment by neeraj15022001** [comment]
Also you can close this one i will be working this one in issue ID #39
