### ISSUE TITLE
Add comments to the code for better readibility 

### ISSUE THREAD

**Issue by mananchawla2005** [mananchawla2005/Hacktoberfest-Repo-Checker#32]
Add comments to the code wherever required which tells about the what the code is doing below it. It would create a better understanding for someone who is looking at code for first time.

**Comment by RaviAnand111** [comment]
Can I you assign it to me ?

**Comment by mananchawla2005** [comment]
@RaviAnand111 Sure, though hacktoberfest has not started yet, u can go through the code till then and add the comment wherever required and can have your pull request after/on 1st october.
