### ISSUE TITLE
HACKTOBERFEST 2021

### ISSUE THREAD

**Issue by mananchawla2005** [mananchawla2005/Hacktoberfest-Repo-Checker#33]
### Welcome to pretember where we maintainers prepare our repositories for upcomming hacktoberfest. The repository will start accepting pr's from October 1st 😄 Till then u can prepare yourselves and get familliar with the code and start working on the already opened issues. I will add some more with time. Happy Hacking! And have fun during the hacktoberfest 😄

**Comment by mananchawla2005** [comment]
**We now have a project in project section which has the upcomming features we would want in this project. U can read through it and suggest some ideas and open a pr.**

**Comment by neeraj15022001** [comment]
please assign this as announcement label
