### ISSUE TITLE
Change the theme and assets of the website for hf 2021

### ISSUE THREAD

**Issue by mananchawla2005** [mananchawla2005/Hacktoberfest-Repo-Checker#34]
The branding for hacktoberfest 2021 has been changed and its more of an orange black grey theme now. The website should be moved to the same theme including the new branding logos.

**Comment by RaviAnand111** [comment]
yeah I can do it. Can you tell me more about it ?

**Comment by Nabhag8848** [comment]
Hey,i am beginner into web dev and want to apply my learnings, I would love to work in this. Can i ?

**Comment by mananchawla2005** [comment]
@Nabhag8848 @RaviAnand111 Go ahead. Work on it. U can find the new branding and color theme on https://hacktoberfest.digitalocean.com/brand-guidelines . Pull requests can be reviewed after/on 1st october

**Comment by RaviAnand111** [comment]
What to do now. How do I watch the homepage ??
![hacktoberfest](https://user-images.githubusercontent.com/59113935/132942474-eecb991d-1f38-46bb-a781-74006514da51.png)

**Comment by RaviAnand111** [comment]
I don't know alot so can you please help me here and tell me, without html file how this project is showing and what is npm and how is this all working. I am still a beginner.

**Comment by mananchawla2005** [comment]
@RaviAnand111 Well, it is something which I can't tell or explain in a paragraph. Google's your best friend. Search about it u still have time left till the hacktoberfest starts. Regarding how u will view the page, well there is a if statement there in index.js file which checks if its october or not. Comment it out while u are working on the home page. :) Happy hacking

**Comment by RaviAnand111** [comment]
ok, Thanks alot

**Comment by RaviAnand111** [comment]
I saw alot of stuff, can you just tell me how to find html find I can't find it anywhere ! Please

**Comment by mananchawla2005** [comment]
@RaviAnand111 U wont find the html. Its basically ejs. But it is html. It's difficult to tell in here. Search about templating engines and ejs.

**Comment by neeraj15022001** [comment]
Is this issue already assigned, if yes please add the assignee

**Comment by mananchawla2005** [comment]
@neeraj15022001 you can work on it :)

**Comment by mananchawla2005** [comment]
You can work on it. I will review the prs after/on 1st. Happy hacking!

**Comment by neeraj15022001** [comment]
Great, just a quick question is there any UI design on your mind ?

**Comment by neeraj15022001** [comment]
I mean how much flexibility i have in UI?

**Comment by mananchawla2005** [comment]
@neeraj15022001 Do your best :) something on the lines of https://hacktoberfest.digitalocean.com/brand-guidelines the official branding and design with little bit of own creativity would perfectly work. Ps: you have the fonts and color theme on the above url

**Comment by neeraj15022001** [comment]
![Desktop - 1](https://user-images.githubusercontent.com/55191873/133085921-ddfbdb3c-97ef-4681-b9c7-0f65a97b5151.png)
How About this design @mananchawla2005

**Comment by neeraj15022001** [comment]
Pattern will be added in background later.

**Comment by neeraj15022001** [comment]
![Desktop - 2](https://user-images.githubusercontent.com/55191873/133086772-cf4a8a82-07af-42db-845a-7d0ac8f2ff0e.png)
Dark Mode can be this

**Comment by mananchawla2005** [comment]
@neeraj15022001 That looks awesome dude. Go ahead. That ui is sick!!!!!! If possible try animating the search box a bit like when clicked expand the width and also the dark mode button.  Just a extra feature, without that too It looks brilliant.

**Comment by mananchawla2005** [comment]
@neeraj15022001 Also yea It would be really nice if it would be responsive as well just like the previous design. :)

**Comment by neeraj15022001** [comment]
> @neeraj15022001 That looks awesome dude. Go ahead. That ui is sick!!!!!! If possible try animating the search box a bit like when clicked expand the width and also the dark mode button.  Just a extra feature, without that too It looks brilliant. 

Animations are already taken care of 👍

**Comment by neeraj15022001** [comment]
He @mananchawla2005 i think we can switch from ejs back to normal html as I don't see much use of it here. Instead we can do that response stuff directly through JavaScript based on api calls. What's your thought on this?

**Comment by mananchawla2005** [comment]
@neeraj15022001 Hey, yea I thought about that. I initially thought of making it in vue js but sticked to ejs as its much easier to manage that in small projects like these. I have some plans to add more features and issues for them once the theme gets changed to the new one. Ejs helps to make the things more organised and a bit more easier in loading the html tags based on conditional statements which is a nice feature. It's basically html so yea I would love to stick with it for now. Ps: from this question I remembered one thing more. Earlier bootstrap was used for the styling stuff. You can go with vanilla css or tailwind css also. :) If u stuck anywhere in understanding the ejs syntax feel free to comment it here. Will be happy to help :)

**Comment by neeraj15022001** [comment]
Okay not a problem i will continue with ejs then.

**Comment by neeraj15022001** [comment]
@mananchawla2005 hey can you check if API is working on your end and if so send me an example of working API
![Screenshot 2021-09-16 at 7 29 04 PM](https://user-images.githubusercontent.com/55191873/133625659-14c43a77-9e43-4409-ab2b-0b317a23a8df.png)

**Comment by mananchawla2005** [comment]
> 
> 
> @mananchawla2005 hey can you check if API is working on your end and if so send me an example of working API
> ![Screenshot 2021-09-16 at 7 29 04 PM](https://user-images.githubusercontent.com/55191873/133625659-14c43a77-9e43-4409-ab2b-0b317a23a8df.png)

Check now

**Comment by mananchawla2005** [comment]
@neeraj15022001 Talk here please. Second Yes it is working idk why its not for u. 
![image](https://user-images.githubusercontent.com/42414965/133892785-a2682834-0a8d-410a-9c9c-93ec3a82fcb9.png)
Third, for testing api use localhost not the deployed version.
Fourth, u are confusing the api with the modal stuff. The api code is different and the "/check" endpoint which checks the repo/pull request on clicking the button is different. Please work on changing the theme of the modal first. Try uncommenting the code and u'll see for yourself that It shows a modal. Hope u get it.

**Comment by mananchawla2005** [comment]
@neeraj15022001 u still working on it?

**Comment by neeraj15022001** [comment]
Yes

**Comment by neeraj15022001** [comment]
Was working with modal part

**Comment by neeraj15022001** [comment]
@mananchawla2005 i will need to work out on backend part as well code is so much messed up there, shall i ? Meanwhile, i will be sharing modal designs shortly. Please try to reply asap.

**Comment by mananchawla2005** [comment]
@neeraj15022001 sure should i open another issue as well? and merge this current pr for now? So that u get more no. of valid prs when hf starts :) thanks for giving out time on this one.

**Comment by neeraj15022001** [comment]
yes sure and just a quick suggestion

**Comment by neeraj15022001** [comment]
![Screenshot 2021-09-21 at 1 09 54 AM](https://user-images.githubusercontent.com/55191873/134064709-241572d0-58f6-4112-a2a5-17b2be7df959.png)
Brand Guidelines are out for hacktoberfest and i found this color combination there, does this look good or previous one is better for dark mode

**Comment by neeraj15022001** [comment]
According to me previous one looks good this is so puchy and irritating but you can share your views as well

**Comment by neeraj15022001** [comment]
![Group 3](https://user-images.githubusercontent.com/55191873/134064992-6d189559-59da-4dab-88d2-9a3012b7d857.png)
![Group 4](https://user-images.githubusercontent.com/55191873/134065000-0a6e7283-15ee-4f5e-8025-99ac742a092d.png)
and these are modal designs

**Comment by mananchawla2005** [comment]
@neeraj15022001 yea u are right the prev is better. These. modal designs look sooo good. I love it.

**Comment by mananchawla2005** [comment]
@neeraj15022001 btw we have a api for checking pull request as well along with repo. This was check endpoint specific and didnt include in the actual api endpoint

**Comment by neeraj15022001** [comment]
I got it i saw backend code yesterday only earlier i thought that it is hosted api and not a custom one

**Comment by mananchawla2005** [comment]
@neeraj15022001 Hey I merging the existing pr to the dev branch and opening up a new issue for backend refactor and modal. Not closing this issue rn, will close it when all's done :)

**Comment by neeraj15022001** [comment]
![Screenshot 2021-09-21 at 1 25 25 PM](https://user-images.githubusercontent.com/55191873/134133345-932724f3-bf1b-4cc7-a549-a77f445cb9c6.png)
Not October screen

**Comment by mananchawla2005** [comment]
@neeraj15022001 greattt 👍 it looks nice

**Comment by mananchawla2005** [comment]
@neeraj15022001 opened another issue #37

**Comment by neeraj15022001** [comment]
@mananchawla2005 you can close this issue

**Comment by mananchawla2005** [comment]
@neeraj15022001 done closed all the remaining issues and prs as well
