### ISSUE TITLE
Add Night Mode and CSS Improvements

### ISSUE THREAD

**Issue by DaviLhlapak** [mananchawla2005/Hacktoberfest-Repo-Checker#4]
I would like to add a night mode and work on the CSS to keep it organized

**Comment by mananchawla2005** [comment]
yeah you can work on it for sure :-) @DaviLhlapakRosa But first lemme merge the pr already made by someone to the dev branch then just clone the dev branch and then make pr to it 👍

**Comment by mananchawla2005** [comment]
Well yeah now you can work on the dev branch @DaviLhlapakRosa

**Comment by mananchawla2005** [comment]
Thanks
