### ISSUE TITLE
Update Branding

### ISSUE THREAD

**Issue by mananchawla2005** [mananchawla2005/Hacktoberfest-Repo-Checker#44]
The website is from last year! would be great if someone can update it to the latest theme for both dark and light themes!

**Comment by detronetdip** [comment]
hey @mananchawla2005  can I work on this?

**Comment by detronetdip** [comment]
Hey @mananchawla2005  I was developing the website for the new theme, I have completed the dark one, and is it necessary to do the light theme as well?

**Comment by mananchawla2005** [comment]
Hey, sorry for the delay! yea sure if u can why not ! It would be streamlined if both designs come from same person... mean while u can make a pull request so that I can review the design before the Hacktoberfest starts! I wil merge the pr only after it starts so that it can count towards your contribution @detronetdip

**Comment by detronetdip** [comment]
Opening a pr soon.

**Comment by detronetdip** [comment]
Hey @mananchawla2005  I have drafted a pull request #46.
