### ISSUE TITLE
Hover Feature on Buttons

### ISSUE THREAD

**Issue by aakashraj01** [mananchawla2005/Hacktoberfest-Repo-Checker#62]
Hey @mananchawla2005 I want to add Hover CSS3 feature on the Check button and also on dark mode button for both light and dark button. I am adding it to make UI better . Would love to contribute in this issue .

Can you please assign it to me under Hacktoberfest 2022 ? :)

**Comment by mananchawla2005** [comment]
Can you explain a bit more about it?

**Comment by aakashraj01** [comment]
Yes @mananchawla2005 . Actually when you hover over Check button and dark/light mode enable button , css color changes a bit on hovering...as there is no hover effect on buttons now.So to make UI of buttons good , I will add Hover effect using CSS3.

**Comment by aakashraj01** [comment]
@mananchawla2005 Can you now assign me this issue :) under Hacktoberfest'22 if you understood this feature what I am goin to add

**Comment by mananchawla2005** [comment]
sure go ahead

**Comment by aakashraj01** [comment]
Hey @mananchawla2005 How can I run your project locally . Because when I tried to run with command node . , its showing this. How can I proceed further , if possible can you let me know 
![IMG_20221003_082841](https://user-images.githubusercontent.com/79682170/193493996-0f3ca0c6-9cd9-4f7a-b784-864fca5742a0.jpg)

**Comment by mananchawla2005** [comment]
read the instructions! u need to provide a secret in environment variablr

**Comment by aakashraj01** [comment]
Hey @mananchawla2005 , I opened the PR for the fix .Have a review and merge it in the project. :)
